### PR TITLE
330 - fix: lectures page issues

### LINKED ISSUE #330: My Lectures action buttons not showing up
image

https://github.com/thenewboston-developers/thenewboston-Frontend/assets/52558124/538d6293-59a9-4848-9b10-c1c35ada3d3b

### PR DESCRIPTION
**Pull request by MAbdurrehman1**
Closes #330

### CODE REVIEW

File: src/pages/University/Lectures/index.tsx [hunk 1]
```diff
@@ -95,14 +92,13 @@ const Lectures: SFC<LecturesProps> = ({className, selfLectures = false}) => {
...
-    const lectureId = lecture.id;
-
-    navigate({
-      pathname: `${PATH_LECTURES}`,
-      search: `?course_id=${courseId}&lecture_id=${lectureId}`,
-    });
+  const updateQueryParam = (paramName: string, value: string) => {
+    const searchParams = new URLSearchParams(location.search);
+    searchParams.set(paramName, value);
+    navigate(`${location.pathname}?${searchParams.toString()}`, {replace: true});
```
Comment (MAbdurrehman1) [inline src/pages/University/Lectures/index.tsx:101]: Just replacing the query param in the URL instead of actually navigating
