### PR TITLE
217 fixed strange scroll behavior

### LINKED ISSUE #217: Fix strange scroll behavior
When scrolling in the feed, the top of the post gets cut off and the scrollbar on the right doesn't move, even as you scroll.

Screen Shot 2024-04-22 at 8 56 23 PM

### PR DESCRIPTION
**Pull request by DesunTech**
Closes #217

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -10,7 +10,9 @@ import initSentry from 'config/sentry';
 import {persistor, store} from 'store';
 import 'styles/fonts.css';
 
-initSentry();
+if (process.env.NODE_ENV !== 'development') {
+  initSentry();
+}
```
Comment (MAbdurrehman1) [inline src/index.tsx:15]: I think we decided not to do this for now.
a PR for this has already been closed

File: src/components/InfiniteScroll/index.tsx [hunk 2]
```diff
@@ -9,11 +9,12 @@ interface InfiniteScrollProps {
...
   dataLength: number;
   hasMore: boolean;
+  heightMargin?: number;
   next: () => void;
 }
 
-const InfiniteScroll: SFC<InfiniteScrollProps> = ({children, dataLength, hasMore, next}) => {
-  const infiniteScrollComponentHeight = window.innerHeight - 105;
+const InfiniteScroll: SFC<InfiniteScrollProps> = ({children, dataLength, hasMore, next, heightMargin = 105}) => {
+  const infiniteScrollComponentHeight = window.innerHeight - heightMargin;
```
Comment (MAbdurrehman1) [inline src/components/InfiniteScroll/index.tsx:17]: Reference comment: https://github.com/thenewboston-developers/thenewboston-Frontend/pull/283#discussion_r1585975667

**Review by MAbdurrehman1 — APPROVED** [review]
Pushed some changes to this
